services:
  - type: pserv
    name: mongodb
    env: docker
    autoDeploy: false
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        sync: false
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false
      - key: MONGO_NON_ROOT_USERNAME
        sync: false
      - key: MONGO_NON_ROOT_PASSWORD
        sync: false
      - key: MONGO_NON_ROOT_DATABASE
        sync: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 5
